// <auto-generated />
using System;
using Gunluk.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gunluk.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230104121208_add-migration 1")]
    partial class addmigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gunluk.DATA.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Örnek Yazi 1",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7546),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7537)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Örnek Yazi 2",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7587),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7586)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Örnek Yazi 3",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7594),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7593)
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Örnek Yazi 4",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7600),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7599)
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Örnek Yazi 5",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7606),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7605)
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Örnek Yazi 6",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7611),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7610)
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Örnek Yazi 7",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7615),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7614)
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Örnek Yazi 8",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7620),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7619)
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Örnek Yazi 9",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7628),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7627)
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Örnek Yazi 10",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7633),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7632)
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Örnek Yazi 11",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7639),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7638)
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Örnek Yazi 12",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7643),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7642)
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Örnek Yazi 13",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7649),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7648)
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Örnek Yazi 14",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7654),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7653)
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Örnek Yazi 15",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7658),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7657)
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Örnek Yazi 16",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7663),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7662)
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Örnek Yazi 17",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7668),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7667)
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Örnek Yazi 18",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7676),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7675)
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Örnek Yazi 19",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7681),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7680)
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Örnek Yazi 20",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7686),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7685)
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Örnek Yazi 21",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7691),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7690)
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Örnek Yazi 22",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7696),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7695)
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Örnek Yazi 23",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7701),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7700)
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Örnek Yazi 24",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7706),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7705)
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Örnek Yazi 25",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7711),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7710)
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Örnek Yazi 26",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7716),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7715)
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Örnek Yazi 27",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7721),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7720)
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Örnek Yazi 28",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7725),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7724)
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Örnek Yazi 29",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7730),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7729)
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Örnek Yazi 30",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7734),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7733)
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Örnek Yazi 31",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7737),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7737)
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Örnek Yazi 32",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7743),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7742)
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Örnek Yazi 33",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7748),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7747)
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Örnek Yazi 34",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7753),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7752)
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Örnek Yazi 35",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7758),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7757)
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Örnek Yazi 36",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7763),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7762)
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Örnek Yazi 37",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7767),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7766)
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Örnek Yazi 38",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7772),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7771)
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Örnek Yazi 39",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7776),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7775)
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Örnek Yazi 40",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7781),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7780)
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Örnek Yazi 41",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7785),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7784)
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Örnek Yazi 42",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7790),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7788)
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Örnek Yazi 43",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7794),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7793)
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Örnek Yazi 44",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7800),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7798)
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Örnek Yazi 45",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7805),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7804)
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Örnek Yazi 46",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7809),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7808)
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Örnek Yazi 47",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7814),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7813)
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Örnek Yazi 48",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7818),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7817)
                        });
                });

            modelBuilder.Entity("Gunluk.DATA.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İş Dünyam"
                        });
                });

            modelBuilder.Entity("Gunluk.DATA.Gonderi", b =>
                {
                    b.HasOne("Gunluk.DATA.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Gunluk.DATA.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
