using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Gunluk.Migrations
{
    public partial class addmigration1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Kategoriler",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Ad = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Kategoriler", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Gonderiler",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Baslik = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: false),
                    Icerik = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Resim = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    OlusturulmaZamani = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DegistirilmeZamani = table.Column<DateTime>(type: "datetime2", nullable: false),
                    KategoriId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Gonderiler", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Gonderiler_Kategoriler_KategoriId",
                        column: x => x.KategoriId,
                        principalTable: "Kategoriler",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Kategoriler",
                columns: new[] { "Id", "Ad" },
                values: new object[,]
                {
                    { 1, "Genel" },
                    { 2, "Gezilerim" },
                    { 3, "Mutfağım" },
                    { 4, "İş Dünyam" }
                });

            migrationBuilder.InsertData(
                table: "Gonderiler",
                columns: new[] { "Id", "Baslik", "DegistirilmeZamani", "Icerik", "KategoriId", "OlusturulmaZamani", "Resim" },
                values: new object[,]
                {
                    { 1, "Örnek Yazi 1", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7546), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7537), null },
                    { 2, "Örnek Yazi 2", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7587), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7586), null },
                    { 3, "Örnek Yazi 3", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7594), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7593), null },
                    { 4, "Örnek Yazi 4", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7600), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7599), null },
                    { 5, "Örnek Yazi 5", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7606), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7605), null },
                    { 6, "Örnek Yazi 6", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7611), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7610), null },
                    { 7, "Örnek Yazi 7", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7615), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7614), null },
                    { 8, "Örnek Yazi 8", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7620), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7619), null },
                    { 9, "Örnek Yazi 9", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7628), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7627), null },
                    { 10, "Örnek Yazi 10", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7633), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7632), null },
                    { 11, "Örnek Yazi 11", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7639), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7638), null },
                    { 12, "Örnek Yazi 12", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7643), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7642), null },
                    { 13, "Örnek Yazi 13", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7649), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7648), null },
                    { 14, "Örnek Yazi 14", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7654), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7653), null },
                    { 15, "Örnek Yazi 15", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7658), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7657), null },
                    { 16, "Örnek Yazi 16", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7663), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7662), null },
                    { 17, "Örnek Yazi 17", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7668), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7667), null },
                    { 18, "Örnek Yazi 18", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7676), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7675), null },
                    { 19, "Örnek Yazi 19", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7681), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7680), null },
                    { 20, "Örnek Yazi 20", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7686), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7685), null },
                    { 21, "Örnek Yazi 21", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7691), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7690), null },
                    { 22, "Örnek Yazi 22", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7696), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7695), null },
                    { 23, "Örnek Yazi 23", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7701), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7700), null },
                    { 24, "Örnek Yazi 24", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7706), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7705), null },
                    { 25, "Örnek Yazi 25", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7711), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7710), null },
                    { 26, "Örnek Yazi 26", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7716), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7715), null },
                    { 27, "Örnek Yazi 27", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7721), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7720), null },
                    { 28, "Örnek Yazi 28", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7725), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7724), null },
                    { 29, "Örnek Yazi 29", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7730), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7729), null },
                    { 30, "Örnek Yazi 30", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7734), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7733), null },
                    { 31, "Örnek Yazi 31", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7737), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7737), null },
                    { 32, "Örnek Yazi 32", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7743), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7742), null },
                    { 33, "Örnek Yazi 33", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7748), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7747), null },
                    { 34, "Örnek Yazi 34", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7753), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7752), null },
                    { 35, "Örnek Yazi 35", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7758), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7757), null },
                    { 36, "Örnek Yazi 36", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7763), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7762), null },
                    { 37, "Örnek Yazi 37", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7767), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7766), null },
                    { 38, "Örnek Yazi 38", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7772), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7771), null },
                    { 39, "Örnek Yazi 39", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7776), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7775), null },
                    { 40, "Örnek Yazi 40", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7781), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7780), null },
                    { 41, "Örnek Yazi 41", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7785), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7784), null },
                    { 42, "Örnek Yazi 42", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7790), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7788), null }
                });

            migrationBuilder.InsertData(
                table: "Gonderiler",
                columns: new[] { "Id", "Baslik", "DegistirilmeZamani", "Icerik", "KategoriId", "OlusturulmaZamani", "Resim" },
                values: new object[,]
                {
                    { 43, "Örnek Yazi 43", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7794), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7793), null },
                    { 44, "Örnek Yazi 44", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7800), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7798), null },
                    { 45, "Örnek Yazi 45", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7805), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7804), null },
                    { 46, "Örnek Yazi 46", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7809), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7808), null },
                    { 47, "Örnek Yazi 47", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7814), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7813), null },
                    { 48, "Örnek Yazi 48", new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7818), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 12, 7, 773, DateTimeKind.Local).AddTicks(7817), null }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Gonderiler_KategoriId",
                table: "Gonderiler",
                column: "KategoriId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Gonderiler");

            migrationBuilder.DropTable(
                name: "Kategoriler");
        }
    }
}
